
import static UI.UIMenu.*;
public class Main {
    public static void main(String[] args) {

          showMenu();
    }




}

//NOTA = MTODO CONSTRUCTOR AYUDA A CREAR NUEVAS INSTANCIAS DE UNA CLASE Y CONSTRUYE UN OBJETO
//NOTA = DOCTOR = ES UN METODO Y MYDOCTOR = OBJETO
//NOTA = DIFERENCIA ENTRE CLASE Y OBJETO = CLASE= MOLDE DONDE DEJAMOS LA ADSTRACION DEL OBJETO = ATRIB Y MTODO
//OBJETO = DEFINIMOS DATOS Y ATRIBUTOS Y LLAMA A LOS METODOS